# Generated by Django 6.0.2 on 2026-03-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='recipe_image',
            field=models.ImageField(upload_to='stored_recipe'),
        ),
    ]
